import { db } from "@/db/db";

const Page = async () => {
  const subject = await db.subject.createMany({

    data:[
    { name: "Bahasa Melayu" },
    { name: "English" },
    { name: "Mathematics" },
    { name: "Science" },
    { name: "Sejarah" },
    { name: "Pendidikan Islam" },
    { name: "Pendidikan Moral" },
    { name: "Reka Bentuk dan Teknologi" },
    { name: "Pendidikan Seni Visual" },
    { name: "Pendidikan Jasmani dan Kesihatan" },
    { name: "Bahasa Cina" },
    { name: "Bahasa Tamil" },
    { name: "ICT" },
    { name: "Additional Mathematics" },
    { name: "Geografi" },
    { name: "Seni Visual" },
    { name: "Kesusasteraan Melayu" },
    { name: "Kesusasteraan Inggeris" },
    { name: "Ekonomi" },
    { name: "Prinsip Perakaunan" },
    { name: "Biology" },
    { name: "Chemistry" },
    { name: "Physics" },
    { name: "Sains Komputer" },
    { name: "Asas Sains Komputer" },
    { name: "Kemahiran Hidup" },
    { name: "Pertanian" },
    { name: "Pengurusan Perniagaan" },
    { name: "Pengajian Keusahawanan" },
    { name: "Bahasa Arab" },
    { name: "French" },
    { name: "German" },
    { name: "Japanese" },
    { name: "Pendidikan Jasmani" },
    { name: "Pendidikan Kesihatan" },
    { name: "Sukan dan Rekreasi" },
    { name: "Advanced Biology" },
    { name: "Advanced Chemistry" },
    { name: "Advanced Physics" },
    { name: "Accounting" },
    { name: "Business Studies" },
    { name: "Law" },
    { name: "Sociology" },
    { name: "Psychology" },
    { name: "Computer Science" },
    { name: "Information Technology" },
    { name: "Engineering Studies" },
    { name: "Philosophy" },
    { name: "History" },
    { name: "Literature" },
    { name: "Linguistics" },
    { name: "Education" },
    { name: "Medicine" },
    { name: "Pharmacy" },
    { name: "Nursing" },
    { name: "Environmental Studies" },
    { name: "Tasawwur Islam" },
    { name: "Tajwid" },
    { name: "Sirah" },
    { name: "Fiqh" },
    { name: "Tauhid" },
    { name: "Quranic Studies" },
    { name: "Hadith Studies" },
    { name: "Global Perspectives" },
    { name: "Environmental Management" },
    { name: "Media Studies" },
    { name: "Drama" },
    { name: "Music" },
    { name: "Dance" },
    { name: "Design and Innovation" }
  ]  }
);

  console.log(subject);

  return <div>Page</div>;
};

export default Page;
